@startuml
entity Hirotake_Yano {             
type: String 
} 
entity Daiso {             
type: String 
} 
entity Daiso_Industries_Company_Limited {             
type: String 
} 
entity dollar_shop_business_model {             
type: String 
} 
Hirotake_Yano -> Daiso : founded
Hirotake_Yano -> Daiso_Industries_Company_Limited : former president of
Hirotake_Yano -> dollar_shop_business_model : pioneer of
@enduml